#!/bin/bash

echo "Event plane analysis"
time=$(date)
echo "Start time : $time"

export seed=1000
jobid=$SLURM_ARRAY_TASK_ID
seed=$((seed+jobid))

# Settings for singularity:
export SINGULARITY_BIND="/projappl/project_2003583,/scratch/project_2003583,$TMPDIR,$FOCAL_ROOT,$ALIROOT_OCDB_ROOT"
export SINGULARITY_SHELL="/bin/bash --norc"
export SINGULARITY_CACHEDIR=$TMPDIR

singularity exec --home $HOME --workdir $TMPDIR /projappl/project_2003583/alidockSingularity_21-06-10.sif alienv setenv O2/latest-dev-o2 -c ./eventplane ${1}.root ${2} ${3} ${4} 

time=$(date)

echo "Finished! ${time}"
