#!/bin/bash

outfile=${1}
indir=${2}

declare -a kinefiles
for file in ${indir}/*/galice.root
do
    kinefiles=(${kinefiles[@]} "$file")
done 

declare -a clustfiles
for file in ${indir}/results_cluster/*.root
do
    clustfiles=(${clustfiles[@]} "$file")
done 

nfiles=${#kinefiles[@]}

for (( i=0; i<$nfiles; i++ ))
#for (( i=0; i<1; i++ ))
do
    cmd="root -b -q 'RunAnalysis.C(\"${kinefiles[i]}\", \"${clustfiles[i]}\", \"${outfile}\")'"
    eval $cmd
done
